name: Go

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:

        - name: Set up Go 1.x
            uses: actions/setup-go@v2
            with:
                go-version: ^1.15

        - name: Check out code into the Go module directory
            uses: actions/checkout@v2

        - name: Install Task
            run: |
                curl -sL https://taskfile.dev/install.sh | sh
                sudo mv ./bin/task /usr/local/bin

        - name: Build with Task
            run: task build
